version: '3.1'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: image-app-spring
    depends_on:
      - db
    ports:
      - "8085:8085"

volumes:
  db_data:
