version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    ports:
      - 3306:3306
  app:
    image: hamzamemmi/gestion-station-ski
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8082:8082
    stdin_open: true
    tty: true